
const allCategories=["Reception","Check-in Process","General Hygiene","Efficiency of Service","Friendliness of Staff","Room Amenities","Taste / Quality of Meals","Ambience and Comfort","Quality of Food","Variety of Food","Presentation of Food","Venue / Setup","Cleanliness","Ambience","Overall Experience"];
const answerOrder=["Very Good","Good","Average","Poor","Very Poor"];
function dateOnly(iso){return new Date(iso).toLocaleDateString()}
function dateTime(iso){return new Date(iso).toLocaleString()}
function filteredItems(){let items=getFeedback();const from=document.getElementById("fromDate").value,to=document.getElementById("toDate").value,type=document.getElementById("reportGuestType").value,id=new URLSearchParams(location.search).get("id");if(id)items=items.filter(i=>i.id===id);if(from)items=items.filter(i=>new Date(i.created_at)>=new Date(from+"T00:00:00"));if(to)items=items.filter(i=>new Date(i.created_at)<=new Date(to+"T23:59:59"));if(type)items=items.filter(i=>i.guest_type===type);return items}
function getSelectedCategory(){return document.getElementById("reportCategory").value}
function renderCategoryOptions(){const s=document.getElementById("reportCategory");allCategories.forEach(c=>{const o=document.createElement("option");o.value=c;o.textContent=c;s.appendChild(o)})}
function distributionFor(items,category){const dist=Object.fromEntries(answerOrder.map(a=>[a,0]));items.forEach(i=>{const r=i.ratings.find(x=>x.category===category);if(r){const a=r.answer||scoreLabel(r.rating);dist[a]=(dist[a]||0)+1}});return dist}
function renderSummary(items){const chosen=getSelectedCategory();let cats=chosen?[chosen]:allCategories.filter(c=>items.some(i=>i.ratings.some(r=>r.category===c)));categorySummary.innerHTML=cats.map(c=>{const d=distributionFor(items,c);return `<div class="category-box"><h3>${c}</h3><div class="distribution">${answerOrder.map(a=>`<div><strong>${d[a]||0}</strong><span>${a}</span></div>`).join("")}</div></div>`}).join("")||"<p>No feedback available for the selected filters.</p>";categorySummary.className="summary-grid"}
function answerRows(item){const chosen=getSelectedCategory();const rows=chosen?item.ratings.filter(r=>r.category===chosen):item.ratings;return rows.map(r=>`<div class="answer-row"><strong>${r.category}</strong><br>${r.answer||scoreLabel(r.rating)}</div>`).join("")}
function detailCard(i){return `<article class="detail-card"><div class="detail-meta"><span><strong>Date:</strong> ${dateOnly(i.created_at)}</span><span><strong>Time:</strong> ${new Date(i.created_at).toLocaleTimeString()}</span><span><strong>Guest Type:</strong> ${i.guest_type}</span>${i.guest_type==="Resident"?`<span><strong>Room:</strong> ${i.room_number}</span><span><strong>Booking:</strong> ${i.booking_type||"-"}</span>`:`<span><strong>Visit Purpose:</strong> ${i.visit_purpose}</span>`}<span><strong>Name:</strong> ${i.name||"Anonymous"}</span></div><div class="detail-answers">${answerRows(i)}</div><p><strong>Comments / Suggestions:</strong> ${i.comments||"-"}</p><p><strong>Status:</strong> ${i.status}</p>${i.ai_analysis?`<div class="ai-report-box"><strong>AI Analysis</strong><br>Sentiment: ${i.ai_analysis.sentiment}<br>Department: ${i.ai_analysis.department}<br>Issue: ${i.ai_analysis.issue_type}<br>Urgency: ${i.ai_analysis.urgency}</div>`:""}${i.resolution_notes?`<p><strong>Resolution Notes:</strong> ${i.resolution_notes}</p>`:""}</article>`}
function renderIndividual(items){const id=new URLSearchParams(location.search).get("id"),sec=document.getElementById("individualReport");if(!id){sec.style.display="none";return}sec.style.display="block";sec.innerHTML=`<h2>Individual Feedback Report</h2>${items[0]?detailCard(items[0]):"<p>Feedback record not found.</p>"}`}
function renderDetailed(items){detailedReport.innerHTML=items.map(detailCard).join("")||"<p>No feedback available for the selected filters.</p>"}
function renderAll(){const items=filteredItems();reportGenerated.textContent="Generated: "+new Date().toLocaleString();renderIndividual(items);renderSummary(items);renderDetailed(items)}
document.addEventListener("DOMContentLoaded",()=>{renderCategoryOptions();renderAll();["fromDate","toDate","reportGuestType","reportCategory"].forEach(id=>document.getElementById(id).addEventListener("change",renderAll));document.getElementById("printReport").addEventListener("click",()=>window.print());document.getElementById("clearFilters").addEventListener("click",()=>{fromDate.value="";toDate.value="";reportGuestType.value="";reportCategory.value="";history.replaceState({},document.title,"reports.html");renderAll()})});
